name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---------- PNPM setup & cache ----------
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile

      # ---------- Build library ----------
      - run: pnpm build

      # ---------- Unit tests ----------
      - run: pnpm vitest run
        env:
          NODE_OPTIONS: --experimental-vm-modules   # vitest + TS esm

  e2e:
    runs-on: ubuntu-latest
    needs: build-test         # wait for build/unit pass
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 8 }
      - run: pnpm install --frozen-lockfile

      # ---------- Install one browser to speed up CI ----------
      - run: pnpm exec playwright install --with-deps chromium

      # ---------- Playwright / Vitest E2E ----------
      - run: pnpm vitest run --runInBand tests/e2e
        env:
          NODE_OPTIONS: --experimental-vm-modules

  smoke-cli:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 8 }
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      # ---------- Run compiled CLI against demo fixtures ----------
      - name: Run a11y-form-tester on fixtures
        run: |
          node bin/a11y-form-tester.js "test/fixtures/*.html"

